// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKT8XNbgT2pBuDG_gjS4OBByGz93iisHY',
    appId: '1:560023258597:web:2a5fa4dfef93b504309b0c',
    messagingSenderId: '560023258597',
    projectId: 'novel-world-3018e',
    authDomain: 'novel-world-3018e.firebaseapp.com',
    storageBucket: 'novel-world-3018e.appspot.com',
    measurementId: 'G-5V5XWWD5KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCodsED65c06X9qbcjfsi_t-zhC_XSfP3I',
    appId: '1:560023258597:android:aa7faccd8880a552309b0c',
    messagingSenderId: '560023258597',
    projectId: 'novel-world-3018e',
    storageBucket: 'novel-world-3018e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj13ybqa6V3OTPhUYzyjBtWnsr-vtJ_z4',
    appId: '1:560023258597:ios:d3a539a0a5b99fe8309b0c',
    messagingSenderId: '560023258597',
    projectId: 'novel-world-3018e',
    storageBucket: 'novel-world-3018e.appspot.com',
    iosBundleId: 'com.novelworld.novelWorld',
  );
}
